#!/bin/sh

## OpenEmbedded environment setup script for CuBox-i
##
## Before starting a build from a build shell; cd to the directory holding
## this file and then source the file:
## . set-oe-env
##

## Meta data versions to use (branch name or commit sha) ##
RELBRANCH=master
POKY_VER=$RELBRANCH
META_OPENEMBEDDED_VER=$RELBRANCH
META_FSL_ARM_VER=$RELBRANCH
META_FSL_ARM_EXTRA_VER=$RELBRANCH


## Set TOPDIR, DL_DIR and DL_MIRROR ##
TOPDIR=$(readlink -f .)
[ "$DOWNLOADS" == "" ] && DOWNLOADS="../downloads"
DL_DIR=$(readlink -f $DOWNLOADS)
if [ ! -d $DL_DIR ]; then
	echo "Error: Downloads directory '$DL_DIR' missing!"
	return 1
fi
DL_MIRROR="file:///home/mats/project/dlmirror/"
export TOPDIR DL_DIR DL_MIRROR

## Create an empty build directory ##
BDIR=$TOPDIR/build
if [ ! -d $BDIR ]; then
	echo "Creating a build directory..."
	mkdir $BDIR
fi

## Auto check-out used layers ##

clone_repo () {
	repo_url="$1"
	checkout="$2"
	repo_name=$(basename "${repo_url}" ".git")

	echo "Checking for $checkout of $repo_name"
	if [ ! -d "$repo_name" ]; then
		git clone -nq "$repo_url" "$repo_name"
		if [ $? -ne 0 ]; then
			echo "Error: Failed to clone $repo_url"
			return 1
		fi
	fi

	cd "$repo_name"

	git checkout -q "$checkout"
	if [ $? -ne 0 ]; then
		echo "Error: Failed to check out $checkout of $repo_name"
		return 1
	fi

	cd - > /dev/null
	return 0
}

clone_repo git://git.yoctoproject.org/poky.git $POKY_VER || return 1
clone_repo git://git.openembedded.org/meta-openembedded $META_OPENEMBEDDED_VER || return 1
clone_repo git://git.yoctoproject.org/meta-fsl-arm $META_FSL_ARM_VER || return 1
clone_repo https://github.com/Freescale/meta-fsl-arm-extra $META_FSL_ARM_EXTRA_VER || return 1


## Source the OE-core supplied environment setup script ##
echo "Processing OE-core internal setup..."
OEROOT=$TOPDIR/poky
. $OEROOT/scripts/oe-buildenv-internal
if [ $? -ne 0 ]; then
	echo "Error: OE-core setup script failed!"
	return 1
fi

## Add to the BitBake environment awareness ##
export BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE TOPDIR DL_DIR DL_MIRROR"

echo "Setup complete!"
